# Generated by Django 5.0.4 on 2024-06-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('online_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name_of_person', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('salary', 'SALARY'), ('adv_salary', 'ADVANCE SALARY'), ('food', 'FOOD'), ('petrol', 'PETROL'), ('return_money', 'RETURN MONEY'), ('rubble', 'RUBBLE'), ('stamping_fee', 'STAMPING FEE'), ('other', 'OTHERS')], max_length=50)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
