# Generated by Django 5.0.4 on 2024-06-22 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_fundin_alter_expenses_name_of_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('mobile1', models.CharField(max_length=10)),
                ('mobile2', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('inventory_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='expenses',
            name='is_employee_expense',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expenses',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.employee'),
        ),
    ]
