# Generated by Django 5.0.4 on 2024-06-22 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_employee_inventory_expenses_is_employee_expense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='account',
        ),
    ]
