# Generated by Django 5.0.4 on 2024-06-24 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_category_alter_expenses_category_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundin',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.subcategory'),
        ),
        migrations.AlterField(
            model_name='fundin',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
    ]
